# set up following the quickstart guide here
#   https://docs.github.com/en/pages/quickstart
# see the following for how to add content
#  https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-content-to-your-github-pages-site-using-jekyll

theme: jekyll-theme-minimal
title: EOTL garden
description: Maybe somewhere down the road a ways
email: eotl_garden@outlook.com
logo: /assets/images/logo.png
